"""Assemble distribution bundles from the canonical artefacts — NON-NORMATIVE.

    python3 -m mtdr_packaging.generate [--check]

Enumerates skills from each package's `package.yaml` and from `skills/shared/`, collects them once
into `skills/packaging/canonical/`, and writes one descriptor and one set of instructions per verified
surface. `--check` regenerates into memory and reports drift instead of writing.

**Adapters translate packaging and invocation, never semantics.** The only transformation performed
here is *collection*: MTDR stores skills two levels deep because they live with the record semantics
they serve (TDR-0023), and no runtime scans that shape. Every `SKILL.md` is copied byte-identical; if
supporting a runtime ever required editing one, the runtime would be unsupported instead.

This module is not normative and defines nothing. See `mtdr_packaging/README.md`.
"""
import filecmp
import glob
import hashlib
import os
import shutil
import subprocess
import sys

import yaml

from .surfaces import SURFACES

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "skills", "packaging")
CANONICAL = os.path.join(OUT, "canonical")


def canonical_skills():
    """Every canonical skill, enumerated from the manifests — never from a hand-maintained list."""
    found = {}
    for manifest in sorted(glob.glob(os.path.join(ROOT, "records", "*", "package.yaml"))):
        m = yaml.safe_load(open(manifest, encoding="utf-8"))
        pkg = os.path.basename(os.path.dirname(manifest))
        for group, names in (m.get("skills") or {}).items():
            for name in names:
                # Resolved by search, not by assumption: a package may nest skills (the decision
                # package groups its eight assurance skills under skills/assurance/).
                hits = glob.glob(os.path.join(ROOT, "records", pkg, "skills", "**", name, "SKILL.md"),
                                 recursive=True)
                if len(hits) != 1:
                    raise SystemExit(f"{manifest} lists {name!r}, which resolves to {len(hits)} "
                                     f"SKILL.md files — the manifest and the tree disagree")
                found[name] = {"path": hits[0], "package": pkg, "group": group}
    for path in sorted(glob.glob(os.path.join(ROOT, "skills", "shared", "*", "SKILL.md"))):
        name = os.path.basename(os.path.dirname(path))
        found[name] = {"path": path, "package": "shared", "group": "record-neutral"}
    return dict(sorted(found.items()))


def digest(path):
    return hashlib.sha256(open(path, "rb").read()).hexdigest()[:16]


def repo_commit():
    try:
        return subprocess.run(["git", "-C", ROOT, "rev-parse", "HEAD"],
                              capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        return "unknown"


def standard_version():
    """The most recent version stated in the changelog — the version a bundle was built from."""
    for line in open(os.path.join(ROOT, "CHANGELOG.md"), encoding="utf-8"):
        if line.startswith("## ["):
            return line.split("[", 1)[1].split("]", 1)[0]
    return "unknown"


def catalogue_yaml(skills):
    lines = ["# Generated by mtdr_packaging — do not edit. Enumerated from each package.yaml.",
             f"skill_count: {len(skills)}", "skills:"]
    for name, info in skills.items():
        lines.append(f"  - name: {name}")
        lines.append(f"    package: {info['package']}")
        lines.append(f"    group: {info['group']}")
        lines.append(f"    source: {os.path.relpath(info['path'], ROOT)}")
        lines.append(f"    sha256_16: {digest(info['path'])}")
    return "\n".join(lines) + "\n"


def provenance_yaml(skills):
    return (
        "# Generated by mtdr_packaging — do not edit.\n"
        "# What this bundle was built from, so a bundle found elsewhere can be traced back.\n"
        f"standard_version: {standard_version()}\n"
        f"commit: {repo_commit()}\n"
        f"skill_count: {len(skills)}\n"
        "source_manifests:\n"
        + "".join(f"  - {os.path.relpath(p, ROOT)}\n"
                  for p in sorted(glob.glob(os.path.join(ROOT, "records", "*", "package.yaml"))))
        + "  - skills/shared/\n"
        "reference_knowledge:\n"
        "  - specification/\n"
        "  - records/decision/specification/\n"
        "  - records/decision/templates/\n"
        "  - records/value/specification/\n"
        "  - records/value/templates/\n"
    )


def surface_yaml(key, s, skills):
    def block(name, items):
        return f"{name}:\n" + ("".join(f"  - {i}\n" for i in items) if items else "  []\n")
    return (
        "# Generated by mtdr_packaging — do not edit. Evidence: skills/packaging/runtime-evidence.md\n"
        f"surface: {key}\n"
        f"title: {s['title']}\n"
        f"class: {s['class']}\n"
        f"confidence: {s['confidence']}\n"
        f"source: {s['source']}\n"
        f"skill_count: {len(skills)}\n"
        + block("project_paths", s["project_paths"])
        + block("personal_paths", s["personal_paths"])
        + block("also_accepts", s["also_accepts"])
        + f"invocation: {s['invocation']}\n"
        f"progressive_disclosure: {s['progressive_disclosure']}\n"
        + block("unverified", s["unverified"])
        + "transformation: collection only — canonical SKILL.md files are copied byte-identical\n"
    )


def surface_readme(key, s, skills):
    paths = s["project_paths"] or s["personal_paths"]
    place = paths[0] if paths else "the runtime's skills directory"
    caution = ""
    if s["unverified"]:
        caution = ("\n> **Not fully verified.** " + "; ".join(s["unverified"]) +
                   ". Confirm against the runtime's own documentation before relying on this, and "
                   "update [`runtime-evidence.md`](../runtime-evidence.md) with what you find.\n")
    return f"""# {s['title']} — distribution bundle

*Generated by `mtdr_packaging`. Do not edit; regenerate.*

This surface is **{s['class']}**: it reads canonical MTDR `SKILL.md` files unmodified. Nothing here
rewrites a skill, and nothing here adds record semantics — a packaging adapter that did either would be
a defect ([TDR-0024](../../../decisions/TDR-0024-packaging-independence.md)).
{caution}
## Install

Copy or link the {len(skills)} collected skills into `{place}`:

```
cp -r skills/packaging/canonical/skills/* {place}
```

Discovery paths this runtime reads:

{chr(10).join('- `' + p + '`' for p in s['project_paths'] + s['personal_paths']) or '- (none recorded)'}

{chr(10).join('- ' + a for a in s['also_accepts'])}

## Invoke

{s['invocation']}

Progressive disclosure: {s['progressive_disclosure']}

## Reference knowledge

**Required, not optional.** The collected skills carry their canonical relative links, which resolve
against the repository layout rather than inside this directory — deliberately: rewriting them would
modify a canonical artefact, which packaging may never do. Deploy the reference knowledge alongside
and the references resolve for the reader; deploy the skills alone and they will not.

The skills point back into the normative layer. Make available the paths listed under
`reference_knowledge` in [`provenance.yaml`](../canonical/provenance.yaml) — the substrate
specifications, and each deployed package's specification and templates.

## The catalogue

{len(skills)} skills, enumerated from the package manifests rather than a hand-maintained list:
[`catalogue.yaml`](../canonical/catalogue.yaml). Every surface ships the same catalogue; a surface
shipping a subset would be a different capability wearing the same name.

## What this bundle does not do

It does not make anything conformant, and using it establishes nothing about the execution that reads
it ([TDR-0032](../../../decisions/TDR-0032-typed-multi-object-conformance.md)). A conforming skill file
does not imply conforming behaviour.
"""


def build():
    """Return {relative path: content} for every generated text file, plus the skill map."""
    skills = canonical_skills()
    files = {
        "canonical/catalogue.yaml": catalogue_yaml(skills),
        "canonical/provenance.yaml": provenance_yaml(skills),
    }
    for key, s in SURFACES.items():
        files[f"{key}/surface.yaml"] = surface_yaml(key, s, skills)
        files[f"{key}/README.md"] = surface_readme(key, s, skills)
    return files, skills


def write():
    files, skills = build()
    shutil.rmtree(os.path.join(CANONICAL, "skills"), ignore_errors=True)
    for name, info in skills.items():
        dest = os.path.join(CANONICAL, "skills", name)
        os.makedirs(dest, exist_ok=True)
        shutil.copyfile(info["path"], os.path.join(dest, "SKILL.md"))
    for rel, content in files.items():
        path = os.path.join(OUT, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        open(path, "w", encoding="utf-8").write(content)
    return skills


def check():
    """Report drift between the committed bundles and what the manifests currently imply."""
    problems = []
    files, skills = build()

    def comparable(text):
        # The recorded commit is the one the bundle was generated at, so it is a generation stamp
        # rather than content. Comparing it would make every bundle stale the moment it was
        # committed. Everything else, including the per-skill digests, is compared exactly.
        return "\n".join(l for l in text.splitlines() if not l.startswith("commit: "))

    for rel, content in files.items():
        path = os.path.join(OUT, rel)
        if not os.path.exists(path):
            problems.append(f"{rel}: missing — regenerate")
        elif comparable(open(path, encoding="utf-8").read()) != comparable(content):
            problems.append(f"{rel}: stale — regenerate")
    collected = {os.path.basename(os.path.dirname(p))
                 for p in glob.glob(os.path.join(CANONICAL, "skills", "*", "SKILL.md"))}
    for extra in sorted(collected - set(skills)):
        problems.append(f"canonical/skills/{extra}: collected but not in any manifest")
    for missing in sorted(set(skills) - collected):
        problems.append(f"canonical/skills/{missing}: in a manifest but not collected")
    for name in sorted(collected & set(skills)):
        dest = os.path.join(CANONICAL, "skills", name, "SKILL.md")
        if not filecmp.cmp(skills[name]["path"], dest, shallow=False):
            problems.append(f"canonical/skills/{name}/SKILL.md: differs from the canonical artefact — "
                            "adapters translate packaging and invocation, never semantics")
    return problems, skills


if __name__ == "__main__":
    if "--check" in sys.argv:
        problems, skills = check()
        for p in problems:
            print(f"DRIFT {p}")
        print(f"{len(skills)} skills; {len(problems)} problem(s)")
        sys.exit(1 if problems else 0)
    s = write()
    print(f"generated {len(SURFACES)} surface bundles over {len(s)} collected skills")
